language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to run tests
script:
  - python -m unittest -v test_module
  - python -m unittest -h
  - python -m unittest discover -p 'Test*.py'