language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - import os,sys
  - lib_path = os.path.abspath('../src')
  - sys.path.append(lib_path)
script:
  - python -m unittest discover -s test/ -p 'Test*.py'
  