#This file was originally generated by PyScripter's unitest wizard

import unittest
from Lexer import *
from Context import *

class TestLexer(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLexerShouldSplitTo2StatementsAndSplitEachToWords(self):
        lex = Lexer(""" hello world
                        1234 9 yx abc """)
        self.assertEqual(lex.lists[0], ["hello", "world"])
        self.assertEqual(lex.lists[1], ["1234", "9", "yx", "abc"])

    def xtestAdvance(self):
        context = Context()
        lexer = Lexer(""" hi krizz
                          987 456 """, [context])
        self.assertEqual(lexer.advance(), 'hi')
        self.assertEqual(lexer.advance(), 'krizz')
        self.assertEqual(lexer.advance(), '987')
        self.assertEqual(lexer.advance(), '456')
        self.assertEqual(lexer.peep(), '456')

if __name__ == '__main__':
    unittest.main()
